# Generated by Django 5.0.2 on 2024-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_gender_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(default='1', max_length=20, unique=True),
        ),
    ]
