# Generated by Django 5.0.2 on 2024-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_student_gender_alter_student_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=20),
        ),
    ]
